### ISSUE TITLE
How to save in Mysql table? 

### ISSUE THREAD

**Issue by Rinlama** [wedgies/jquery-emoji-picker#56] opened 2017-01-10 18:22 UTC
I created a column collation utf8mb4_unicode_ci, but it just save as ?????????

**Comment by makenai** [comment] 2017-01-10 18:23
Duplicate of #55 - sorry this is out of scope for this project.

**Closed by makenai** 2017-01-10 18:23 UTC

**Comment by vishnu1991** [comment] 2017-02-07 17:51
@Rinlama Just go thru this answer on stackoverflow http://stackoverflow.com/a/39465494 
I have tried this  and its working fine !
